package br.com.pousda.pousada.notificacoes.core.domain.enums;

public enum NotificationType {
    // Reservas
    RESERVA_CRIADA, RESERVA_ATUALIZADA, RESERVA_CONFIRMADA, RESERVA_CANCELADA,
    RESERVA_RESUMO_VESPERA, RESERVA_HOJE_PENDENTE, RESERVA_ULTIMA_CHAMADA, RESERVA_NAO_CONFIRMADA_CANCELADA,

    // Hospedagens
    HOSPEDAGEM_CHECKOUT_LEMBRETE_11H, HOSPEDAGEM_CRIADA, HOSPEDAGEM_ATUALIZADA, HOSPEDAGEM_ALERTA_RESERVA_AMANHA,
    HOSPEDAGEM_CHECKOUT_AUTOMATICO, HOSPEDAGEM_CHECKOUT_MANUAL,

    // Quartos
    QUARTO_ENTROU_MANUTENCAO, QUARTO_7DIAS_EM_MANUTENCAO, QUARTO_VOLTOU_DISPONIVEL,
    QUARTO_CRIADO, QUARTO_ATUALIZADO, QUARTO_EXCLUIDO,

    // Financeiro
    FIN_LANCAMENTO_CRIADO, FIN_LANCAMENTO_ATUALIZADO, FIN_LANCAMENTO_CANCELADO,

    // Usuários
    USUARIO_CRIADO, USUARIO_ATUALIZADO, USUARIO_STATUS_ALTERADO, USUARIO_SENHA_RESETADA,
    USUARIO_AUTO_EXCLUIDO, USUARIO_EXCLUIDO, USUARIO_ATUALIZOU_PROPRIO_PERFIL, USUARIO_SENHA_ATUALIZADA_PELO_PROPRIO,
    USUARIO_EXCLUSAO_EM_DOIS_DIAS, USUARIO_EXCLUIDO_AUTOMATICAMENTE, USUARIO_SENHA_ATUALIZADA_NO_PRIMEIRO_LOGIN,
    USUARIO_SEUS_DADOS_ATUALIZADOS,

    // Metas
    META_RESUMO_SEMANAL, META_RESUMO_MENSAL
}
